server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userservicefallback

        - id: contact-service
          uri: lb://contact-service
          predicates:
           - Path=/contacts/**
          filters:
            - name: CircuitBreaker
              args:
                name: contact-service
                fallbackuri: forward:/contactservicefallback

        - id: epay-cbs
          uri: lb://epay-cbs
          predicates:
            - Path=/cbs/**
          filters:
            - name: CircuitBreaker
              args:
                name: epay-cbs
                fallbackuri: forward:/epaycbsservicefallback

        - id: epay-abs
          uri: lb://epay-abs
          predicates:
            - Path=/abs/**
          filters:
#            - name: CircuitBreaker
              args:
                name: epay-abs
                fallbackuri: forward:/epayabsservicefallback

hystrix:
  command:
    fallbackcmd:
      eecution:
        isolation:
          thread:
            timeoutInMillieseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


# Fallback for services: Like if user-service is down then the message will display that
# user-service is currently not unavailable
# Implentation: 1. Hystrix (Old), 2. Resillience4j
